fix: image caching and LastModified antics
varianter/chewbacca pull request #74
Opened 2023-05-10 18:56 UTC by mikaelbr

Fixes logic around last modified by using headers on GET request instead. It looks like S3 doesn't support HEAD requests and OPTIONS requests don't work as expected. But using If-Modified-Since is good

2023-05-10 20:06 UTC, adriansberg approved these changes
Looks good. Have not tested.

2023-05-10 20:40 UTC, nikolaia requested changes

2023-05-10 20:40 UTC, nikolaia commented on src/BlobStorage/Repositories/BlobStorageRepository.cs
> +        }
Siden vi sjekker at cv image url er satt her https://github.com/varianter/chewbacca/blob/main/src/Orchestrator/Service/OrchestratorService.cs#L46 burde dette kun skje ved nettverksfeil etc, ikke fordi bildet ikke finnes. Foreslår vi beholder denne og helder endrer til `if (cv !=null)` på linja jeg lenka - så får vi inn alle uten bilde og. Så får klientene selv håndtere at det finnes ansatte uten bilde.

Ville i så fall oppdatert logginga her til å si hvilken statuskode det er, så vi vet om det er fordi bildet ikke fantes (404) eller om det skjedde noe galt.

2023-05-10 20:54 UTC, nikolaia commented on src/BlobStorage/Repositories/BlobStorageRepository.cs
> +                    message.Headers.IfModifiedSince = blobLastModifiedDate;
Begynte å tenke om dette ikke bare kunne vært

```
        if (await blockBlobClient.ExistsAsync())
        {
            var props = await blockBlobClient.GetPropertiesAsync();
            message.Headers.IfModifiedSince =
                DateTimeOffset.TryParse(props.Value?.Metadata?[BlobMetadataLastModifiedKey],
                    out DateTimeOffset blobLastModifiedDate)
                    ? blobLastModifiedDate
                    : null;
        }
```

2023-05-11 08:17 UTC, nikolaia approved these changes

2023-05-11 08:18 UTC, merged